name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12' ]

    steps:
    - uses: actions/checkout@v4
      with:
        # Ensure a dynamic version is assigned
        fetch-tags: true
        fetch-depth: 20

    - name: Cache air
      uses: actions/cache@v4
      with:
        path: ~/audb/air/1.4.2
        key: air-1.4.2

    - name: Cache cough-speech-sneeze
      uses: actions/cache@v4
      with:
        path: ~/audb/cough-speech-sneeze/2.0.1
        key: cough-speech-sneeze-2.0.1

    - name: Cache emodb
      uses: actions/cache@v4
      with:
        path: ~/audb/emodb/1.4.1
        key: emodb-1.4.1

    - name: Cache micirp
      uses: actions/cache@v4
      with:
        path: ~/audb/micirp/1.0.0
        key: micirp-1.0.0

    - name: Cache musan
      uses: actions/cache@v4
      with:
        path: ~/audb/musan/1.0.0
        key: musan-1.0.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Ubuntu - install libsndfile
      uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05  # v1.6.0
      with:
        packages: libsndfile1 ffmpeg sox libavcodec-extra
        version: 1.0

    - name: Test building documentation
      run: uv run python -m sphinx docs/ docs/_build/ -b html

    - name: Check links in documentation
      run: uv run python -m sphinx docs/ docs/_build/ -b linkcheck -W
